begin;

create extension if not exists citext with schema extensions;

create table if not exists public.vocabulary (
  id bigint generated by default as identity primary key,
  word extensions.citext not null unique,
  lang text not null default 'en' check (lang = 'en'),
  translation text not null check (length(trim(translation)) > 0),
  meaning text not null check (length(trim(meaning)) > 0),
  example text not null check (length(trim(example)) > 0),
  level text not null check (level in ('beginner', 'intermediate', 'advanced')),
  tags text[] not null check (cardinality(tags) = 2),
  created_by text not null default 'seed',
  created_at timestamptz not null default now()
);

create table if not exists public.review_events (
  id bigint generated always as identity primary key,
  client_event_id uuid not null unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  vocabulary_id bigint not null references public.vocabulary(id) on delete restrict,
  rating text not null check (rating in ('good', 'weak')),
  grade smallint not null check (grade between 0 and 5),
  reviewed_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists public.user_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  vocabulary_id bigint not null references public.vocabulary(id) on delete cascade,
  repetition integer not null default 0 check (repetition >= 0),
  ease numeric(6, 3) not null default 2.5 check (ease >= 1.3),
  interval_days integer not null default 1 check (interval_days >= 1),
  last_review_at timestamptz,
  next_review_at timestamptz,
  last_rating text check (last_rating is null or last_rating in ('good', 'weak')),
  updated_at timestamptz not null default now(),
  primary key (user_id, vocabulary_id)
);

create table if not exists public.user_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  daily_limit integer not null default 10 check (daily_limit between 1 and 100),
  timezone text not null default 'Asia/Riyadh' check (length(trim(timezone)) > 0),
  updated_at timestamptz not null default now()
);

create index if not exists review_events_user_reviewed_at_idx
  on public.review_events (user_id, reviewed_at desc);
create index if not exists review_events_vocabulary_idx
  on public.review_events (vocabulary_id);
create index if not exists user_progress_due_idx
  on public.user_progress (user_id, next_review_at);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists user_progress_set_updated_at on public.user_progress;
create trigger user_progress_set_updated_at
before update on public.user_progress
for each row execute function public.set_updated_at();

drop trigger if exists user_settings_set_updated_at on public.user_settings;
create trigger user_settings_set_updated_at
before update on public.user_settings
for each row execute function public.set_updated_at();

alter table public.vocabulary enable row level security;
alter table public.review_events enable row level security;
alter table public.user_progress enable row level security;
alter table public.user_settings enable row level security;

commit;
